/**
 * Old / guessed paths that 404 on Apache (no prerendered file).
 * Keep in sync with public/.htaccess, .htaccess, and public/_redirects.
 */
export const LEGACY_REDIRECTS: Record<string, string> = {
  '/about': '/guide',
  '/experiences/luxury-beach-resorts': '/experiences/luxury-resorts',
  '/blog/undefined': '/blog',
  '/blog/havelock-vs-neil-island-guide': '/blog/havelock-vs-neil-island-guide-2026',
  '/blog/andaman-7-day-itinerary': '/blog/7-day-andaman-itinerary',
  '/blog/andaman-itinerary-7-days': '/blog/7-day-andaman-itinerary',
  '/blog/andaman-best-time': '/blog/best-time-to-visit-andaman',
  '/blog/best-time-visit-andaman': '/blog/best-time-to-visit-andaman',
  '/blog/andaman-budget-guide': '/blog/andaman-budget-travel-guide',
  '/blog/cheap-andaman-packages': '/blog/andaman-budget-travel-guide',
  '/blog/andaman-scuba-guide': '/blog/andaman-scuba-diving-guide',
  '/blog/andaman-scuba-prices-2025': '/blog/andaman-scuba-prices-2026',
  '/blog/andaman-top-things-to-do': '/blog/andaman-top-things-to-do-2025',
  '/blog/top-things-to-do-in-andaman': '/blog/andaman-top-things-to-do-2025',
  '/blog/top-things-to-do-andaman': '/blog/andaman-top-things-to-do-2025',
  '/blog/top-things-to-do-andaman-2026': '/blog/andaman-top-things-to-do-2025',
  '/blog/andaman-luxury-resorts-2025': '/blog/andaman-luxury-resorts-2026',
  '/blog/port-blair-one-day-plan': '/blog/port-blair-one-day-itinerary',
  '/blog/best-beach-destination-india': '/blog/best-beach-destinations-india',
  '/blog/havelock-island-guide': '/blog/havelock-island-travel-guide-2026',
  '/blog/port-blair-travel-guide': '/blog/port-blair-travel-guide-2026',
  '/blog/andaman-international-guide': '/blog/andaman-islands-international-travel-guide-2026',
  '/blog/andaman-solor-trip-guide': '/blog/andaman-solo-trip-guide',
  // Duplicate posts: 301 to the indexed canonical (stronger than noindex + canonical)
  '/blog/is-andaman-safe-2026': '/blog/is-andaman-safe-for-tourists',
  '/blog/a-food-lovers-guide-to-andaman': '/blog/andaman-food-guide',
  '/blog/andaman-vegetarian-food-guide-2026': '/blog/vegetarian-food-in-andaman',
  '/blog/andaman-internet-connectivity-guide-2026': '/blog/mobile-network-internet-in-andaman',
  '/blog/andaman-ferry-guide-2026': '/blog/andaman-ferry-booking-guide',
  '/blog/andaman-family-itinerary-2026': '/blog/andaman-family-itinerary',
  '/blog/family-friendly-andaman-kids': '/blog/andaman-family-itinerary',
  '/blog/andaman-packing-list-checklist': '/blog/what-to-pack-for-andaman-trip',
  '/blog/sustainable-packing-list-2026': '/blog/what-to-pack-for-andaman-trip',
  '/blog/andaman-scuba-diving-2026': '/blog/andaman-scuba-diving-guide',
  '/blog/scuba-diving-andaman-guide': '/blog/andaman-scuba-diving-guide',
  '/blog/top-10-things-to-do-andaman-2025': '/blog/andaman-top-things-to-do-2025',
  '/blog/bali-vs-andaman-comparison': '/blog/andaman-vs-bali',
  '/blog/best-time-visit-thailand': '/blog/best-time-to-visit-andaman',
  '/blog/andaman-tourism-trends-2026': '/blog/first-timers-guide-andaman-2026',
  '/blog/hidden-andaman-facts-2026': '/blog/first-timers-guide-andaman-2026',
  '/blog/best-beach-award-2024': '/blog/radhanagar-beach-guide-2026',
  '/blog/new-ferry-services-2026': '/blog/andaman-ferry-booking-guide',
  '/blog/island-tourism-festival-2026': '/blog/first-timers-guide-andaman-2026',
  '/blog/new-eco-resorts-andaman-2026': '/blog/andaman-luxury-resorts-2026',
  '/destinations/saddle-peak': '/destinations/ross-smith-islands',
  '/destinations/north-andaman-destinations': '/destinations/ross-smith-islands',
};
